"""empty message

Revision ID: 0aa90148fa76
Revises: 63dba2060f71
Create Date: 2017-08-13 14:32:03.801149

"""

# revision identifiers, used by Alembic.
revision = '0aa90148fa76'
down_revision = '63dba2060f71'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equation', sa.String(), nullable=True),
    sa.Column('words', sa.String(), nullable=True),
    sa.Column('promotedwords', sa.String(), nullable=True),
    sa.Column('access_times', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equation')
    )
    op.drop_table('results')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='results_pkey')
    )
    op.drop_table('equation')
    # ### end Alembic commands ###
